platform :ios, '8.0'

target 'PodDemo' do
   pod 'HRLivingBodyDetection/ZHSdkLib',:git=>'https://gitee.com/bizhanlu/HRLivingBodyDetection.git',:tag=>'1.0.3'
  pod 'HRBocSignContract',:path=>'../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64 armv7"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


