platform :ios, '8.0'

#source 'https://gitee.com/bizhanlu/BZLSpecs.git'
#source 'https://cdn.cocoapods.org/'

target 'PodDemo' do
  #pod 'HRBocSignContract' , :path => '../'
  pod 'HRBocSignContract',:git=>'https://gitee.com/bizhanlu/HRBocSignContract.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64e arm64 armv7 armv7s"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


