platform :ios, '8.0'

target 'PodDemo' do
  pod 'HRBocSignContract' , :path => '../'
  #pod 'HRBocSignContract',:git=>'https://github.com/bizhanlu/BZLSpecs.git',:tag=>'~>2.1.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "arm64e arm64 armv7 armv7s"
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


